import type { Metadata } from 'next'
import { Inter, EB_Garamond, Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({})

export const metadata: Metadata = {
  title: 'Templates',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
